version: '3'
services:
  frontend:
    build:
      context: ./frontend/ecommerce
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproj.settings
      - SECRET_KEY="django-insecure-9t1pstl0+b$+*zr*2*typ5^bhi208\(ewp8z-+\)h1lr+aqe+9e0"

    command: python manage.py runserver 0.0.0.0:8000