# Generated by Django 4.0.6 on 2023-02-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amunt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
