# Generated by Django 4.1.5 on 2023-01-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desc", models.CharField(blank=True, max_length=50, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("createdTime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Colors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desc", models.CharField(blank=True, max_length=50, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("createdTime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
