# Generated by Django 4.0.6 on 2023-02-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_amunt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amunt',
            new_name='amount',
        ),
    ]
