# Generated by Django 4.1.5 on 2023-01-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_cars_colors"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cars",
        ),
        migrations.DeleteModel(
            name="Colors",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
