# Generated by Django 4.0.6 on 2023-02-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_amunt_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
    ]
