# Generated by Django 4.1.5 on 2023-01-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/placeholder.png", null=True, upload_to=""
            ),
        ),
    ]
